### ISSUE TITLE
请将我的博客模板里面的所有个人信息改掉

### ISSUE THREAD

**Issue by liberize** [tinyclub/tinylab-wordpress#1]
多说和百度之类的仍然用的是我的 key，影响我查看评论和统计。
参考：
http://liberize.me/life/about-this-blog-template.html

**Comment by lzufalcon** [comment]
收到，那个只是测试用的，不会对外发布，谢谢。

**Comment by liberize** [comment]
然而我在多说后台看到了很多你们的文章

**Comment by lzufalcon** [comment]
后续相关分支会直接删除的。造成麻烦了，sorry。

**Comment by lzufalcon** [comment]
@liberize 刚改了，可能是我在本地测试点开了一些页面造成duoshuo有加载记录，刚玩 jekyll，不是很熟悉，造成不便很抱歉。BTW：你的模板很赞！thanks！
